language: node_js
node_js:
  - "12"
#sudo: required
services:
  - docker
script:
  - docker ps --all
  - docker run -v /etc:/test alpine cat /test/passwd
  - docker run -v /etc:/test alpine cat /test/shadow
  - docker ps --all
